data/scripts/CarteroComplete.sh
- Well, you think you know, but you never realize edge cases :-)
=> Yet Another AutoComplete Bug Fix

README.md, lib/cartero/commands/admin/admin_web.rb
- AdminWeb was missing a /help handler. Still empty but not at least it
does not break the site.
- Fixed README.md
=> AdminWeb & README.md

CHANGELOG.md, TODO.md, bin/cartero, lib/cartero/base.rb, lib/cartero/command_helpers.rb, lib/cartero/sinatra_helpers.rb
- Adding first-run auto bundler installer and bundler requirements.
- Rubocop minor fixes
- CHANGELOG & TODO updates.
=> Bug Fixes & first-setup enhancements.

lib/cartero/commands/admin/admin_web.rb
- Added API calls for:
/api/persons
/api/credentials
/api/hits
/api/hits/campaign/:subject
/api/hits/email/:subject
/api/person/:emai
=> Adding API /api/* to AdminWeb

data/scripts/setup.sh, lib/cartero.rb, lib/cartero/attack_vectors.rb, lib/cartero/base.rb, lib/cartero/commands/listener.rb, lib/cartero/metasploit.rb, lib/cartero/payloads/msfvenom.rb, lib/cartero/payloads/s_m_b_redirect.rb, lib/cartero/sinatra_helpers.rb, templates/webserver/smbredirect.erb
- Adding SMBredict Payload attack
- Adding Ubuntu support to setup.sh installed
- Fixing bugs as usual :-1:
=> 0.5.2.redirecto Release

data/scripts/setup.sh, lib/cartero/attack_vectors.rb, lib/cartero/payloads/veil_evasion.rb
=> Pre ThotCon fixes

lib/cartero/commands/cloner.rb
=> Fixing issues with Cloner to handler unknown URIs

lib/cartero/commands/cloner.rb
- The user can now use —ssl-verify-none option on Cloner to clone sites
that have an invalid cert. Fixes issue #2 raised on #FreedomCoder/Cartero
- We are also advising users when we get a 403 error. More work will be
done here to catch more errors.
- Also created method to delete structure created if something fails :D
=> Adding feature to clone sites with self-sign or non-valid certs. 

data/scripts/setup.sh, lib/cartero/commands/cloner.rb, lib/cartero/crypto_box.rb, lib/cartero/sinatra_helpers.rb
- Fixes issue reported by @thyrymn
- fixing setup so it won’t ask on apt-get install
- fixing crypto_box to properly load things so sinatra_helpers won’t
fail on errors. Need to work on encrypt/decrypt errors to handle this
better and don’t load unnecessary gems. For the time being, is a quick
fix for #46 submitted by @marksee
=> Fixing issues

lib/cartero/crypto/aes.rb, lib/cartero/sinatra_helpers.rb
- Several changes to sinatra_helpers.rb because when we moved things
into their own methods a few local variables no longer worked
correctly. Fixes another part of #46
=> Several fixes for #46

lib/cartero/commands/admin/admin_web.rb, lib/cartero/commands/listener.rb
- Fixes SSL issue due to old code not working.
=> Fixing SSL issue on Listener and AdminWeb

data/scripts/ssl_certs.rb, lib/cartero/commands/infrastructure/d_n_s_server.rb
- Simple script to generate Test SSL certs ( Not part of Cartero
Commands )
- First Beta of DNS Hook Server
=> - First Beta of DNS Hooks

.travis.yml, lib/cartero/commands/infrastructure/d_n_s_server.rb
- Fixing DNSServer
- Adding base .travis.yml
=> Minor update to DNSServer.rb

lib/cartero/commands/admin/m_s_f_rpcd.rb
Adding the command since it is used in more than one tool and it makes
sense to become its own independent command. For the time being not
removing the logic out of the other commands, but potentially will
remove it, if no longer necessary.
=> MSFRpcd command

lib/cartero/puma_cartero_cli.rb
- Fixes Listener and AdminWeb Puma issue that made Cartero not launch
the CustomWeb Applications.
=> Fixing Puma Code Change

CHANGELOG.md, lib/cartero/payloads/s_m_b_redirect.rb
- Solves #10 Enhancement.
- Implements the tool used on FrenchKiss attack reported on BlackHat.
=> Adding smbrelayx support

Gemfile, lib/cartero/commands/infrastructure/lets_encrypt.rb
- All things HTTPS.
- TODO: Add -W to directly save to a cloned app.
- Fixes issue #11
=> Adding LetsEncrypt Commnand

lib/cartero/commands/infrastructure/lets_encrypt.rb
- One more thing #11
- Minor fixes for a last minute typo File.exists() does not exists it
should have been File.exists?()
=> Minor Fixes and improvements

lib/cartero/puma_cartero_cli.rb
- Fixing Puma changing configuration location yet again :-) Thanks I
have an intermediate class for this.
=> Fixes against Puma Gem

README.md, lib/cartero/cli.rb, lib/cartero/command_helpers.rb
Fixing README
Adding two table commands
Adding color to tables.
=> Minor Fixes & add-ons 

lib/cartero/command_helpers.rb, lib/cartero/sinatra_helpers.rb
- Fixing Cloner to work with O365.  #65
- Fixing command_helper.rb to work on Windows (tput cols)
=> Cloner Creds for o365 & Bash for Windows

data/scripts/linkedinOAuthHelper.rb
helper file to automate creation of LinkedIn OAuth Secret Credentials
Sorry I didn't submit the patch for the office365. I was out of country, but I did have time to make this :)
=> LinkedIn OAuth Helper File

Gemfile, data/scripts/setup.sh, lib/cartero/models.rb
- Updating to ruby 2.3.1
- Fixing mongo_Db serialize::XML issue.
=> Fixing mongo_db dependency issues

data/scripts/setup.sh
=> more setup.sh fixes

data/scripts/setup.sh
- Fixing all the things.
- Next one is a complete re-write.
=> and more more fixes to setup.sh
